*140103 SET TIME ZONE=+00:00**/;

/*140014 SET @OLD_UNIQUE_CHECKS @@UNIQUE CHECKS, UNIQUE CHECKS/;

/*140014 SET @OLD_FOREIGN_KEY_CHECKS @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS-0 */;

/*140101 SET @OLD_SQL_MODE=@@SQL NODE, SQL_NODE=NO_AUTO_VALUE_ON_ZERO* */;

/*140111 SET @OLD_SQL_NOTES @@SQL_NOTES, SQL NOTES 0 */;

Table structure for table 'cidade

DROP TABLE IF EXISTS cidade";

/*140101 SET @saved_cs_client @@character set_client */;

/*150503 SET character_set_client utf8mb4 */;

CREATE TABLE `cidade" (

"idcidade" int unsigned NOT NULL AUTO INCREMENT,

nome varchar(45) NOT NULL,

'pais_idpais int NOT NULL,

PRIMARY KEY (`Idcidade),

KEY fk cidade_pais_idx (pais_idpais")

) ENGINE InnoDB AUTO INCREMENT 4 DEFAULT CHARSET utf8mb3;

/*140101 SET character_set_client = @saved_cs_client */;

Dumping data for table 'cidade

LOCK TABLES cidade" WRITE;

/*140000 ALTER TABLE cidade DISABLE KEYS */;

INSERT INTO cidade VALUES (1, 'Guarulhos", 1), (2, 'Angra dos Reis', 1), (3, 'Rio de Janeiro",1);

/*140000 ALTER TABLE cidade ENABLE KEYS */;

UNLOCK TABLES;

/*140103 SET TIME ZONE-BOLD TIME ZONE */;

/*140101 SET SQL MODE @OLD_SQL_NODE */;

/*140014 SET FOREIGN_KEY_CHECKS @OLD_FOREIGN_KEY_CHECKS */;

/*140014 SET UNIQUE CHECKS BOLD UNIQUE CHECKS */;

/*140101 SET CHARACTER SET CLIENT BOLD CHARACTER SET CLIENT */;

/*140101 SET CHARACTER_SET_RESULTS-@OLD_CHARACTER_SET_RESULTS*/;

/*140101 SET COLLATION CONNECTION-BOLD COLLATION_CONNECTION */;

/*140111 SET SQL_NOTES BOLD_SQL_NOTES */;

Dump completed on 2025-04-01 9:01:50

MySQL dump 10.13 Distrib 8.0.32, for Win64 (x86_64)

Host: localhost

Database: bdviagem

Server version 8.0.32

/*140101 SET @OLD_CHARACTER_SET_CLIENT @@CHARACTER_SET_CLIENT */;

/*140101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;

/*140101 SET @OLD_COLLATION_CONNECTION-@@COLLATION_CONNECTION */;

/*150503 SET NAMES utf8 */;

/*140103 SET @OLD_TIME_ZONE @@TIME_ZONE */;

/*140103 SET TIME ZONE=*+00:00' */;

/*140014 SET @OLD_UNIQUE_CHECKS-@@UNIQUE_CHECKS, UNIQUE_CHECKS-0*/;

/*140014 SET @OLD_FOREIGN_KEY_CHECKS @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS-0 */;

/*140101 SET BOLD SOL MODE @@SQL MODE, SQL MODE='NO AUTO VALUE ON ZERO**/;

/*140111 SET @OLD_SQL_NOTES @@SQL NOTES, SQL NOTES-B */;

Table structure for table cidade

DROP TABLE IF EXISTS cidade;

/*140101 SET @saved_cs_client - @@character_set_client */;

/*150503 SET character_set_client utf8mb4 */;

CREATE TABLE cidade" (

idcidade int unsigned NOT NULL AUTO INCREMENT,

nome varchar(45) NOT NULL,

"pais_idpais int NOT NULL,

PRINARY KEY (`idcidade), KEY *fk_cidade_pais_idx ("pais_idpais")

) ENGINE=InnoDB AUTO INCREMENT 4 DEFAULT CHARSET=utf8mb3;

/*140101 SET character_set_client @saved_cs_client */;

Dumping data for table "cidade

LOCK TABLES 'cidade WRITE;

/*140000 ALTER TABLE "cidade DISABLE KEYS */;

INSERT INTO cidade VALUES (1, 'Guarulhos", 1), (2, 'Angra dos Reis', 1), (3, 'Rio de Janeiro,1);

/*140000 ALTER TABLE cidade ENABLE KEYS */;

Activate Windows

Go to Settings to activate Windows

MySQL dump 10.13 Distrib 8.0.32, for Win64 (x86_64)

Host: localhost Database: bdviagem

Server version 8.0.32

/*140101 SET @OLD_CHARACTER_SET_CLIENT @@CHARACTER_SET_CLIENT */;

/*140101 SET BOLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS*/;

/*140101 SET @OLD_COLLATION_CONNECTION @@COLLATION_CONNECTION */;

/*150503 SET NANES utf8 */;

/*140103 SET @OLD_TIME_ZONE @@TIME_ZONE */;

/*140103 SET TIME ZONE=+00:00 */;

/*140014 SET @OLD_UNIQUE_CHECKS @@UNIQUE CHECKS, UNIQUE CHECKS=0"/:

/*140014 SET @OLD_FOREIGN_KEY_CHECKS @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS-01;

/*140101 SET @OLD_SQL_MODE @@SQL_MODE, SOL MODE=NO_AUTO_VALUE_ON_ZERO */;

/*140111 SET @OLD_SQL_NOTES @@SQL NOTES, SQL NOTES-0*/;

Table structure for table "voos"

DROP TABLE IF EXISTS voos";

/*140101 SET @saved_cs_client @character_set_client */;

/*150503 SET character_set_client utf8mb4 */;

CREATE TABLE voos (

idvoos int unsigned NOT NULL AUTO INCREMENT,

destino varchar(60) NOT NULL,

ida date NOT NULL,

data volta date NOT NULL,

"hora saida time NOT NULL,

"horar cheg" time NOT NULL,

"hora_media" time NOT NULL, idcidade int NOT NULL,

PRIMARY KEY (`idvoos'), KEY fk_voos_cidadel_idx" ("idcidade")

) ENGINE-InnoDB AUTO INCREMENT 2 DEFAULT CHARSET=utf8mb3;

/*140101 SET character set client @saved_cs client */;

Dumping data for table "voos

Activate Windows

Go
MySQL dump 10.13 Distrib 8.0.32, for Win64 (x86_64)

Host: localhost Database: bdviagem

Server version 8.0.32

/*140101 SET BOLD CHARACTER SET CLIENT @@CHARACTER SET CLIENT */;

/*140101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;

/*140101 SET @OLD COLLATION CONNECTION @@COLLATION CONNECTION */;

/*150503 SET NAMES utf8 */;

/*140103 SET @OLD_TIME_ZONE @@TIME ZONE */;

/*140103 SET TIME ZONE=+00:00 */;

/*140014 SET @OLD_UNIQUE_CHECKS-@@UNIQUE_CHECKS, UNIQUE_CHECKS=0*/;

/*140014 SET SOLD FOREIGN KEY CHECKS-BBFOREIGN KEY CHECKS, FOREIGN KEY CHECKS-*/;

/*140101 SET @OLD_SQL_MODE @@SQL NODE, SQL MODE=NO_AUTO_VALUE_ON_ZERO* */;

/*140111 SET BOLD SQL NOTES GOSOL NOTES, SQL NOTES-0 */;

Dumping routines for database "bdviagem"

/*140103 SET TIME ZONE @OLD_TIME_ZONE */;

/*140101 SET SQL NODE BOLD_SQL_NODE*/;

/*140014 SET FOREIGN_KEY_CHECKS @OLD_FOREIGN_KEY_CHECKS */;

/*140014 SET UNIQUE_CHECKS @OLD_UNIQUE_CHECKS */;

/*140101 SET CHARACTER_SET_CLIENT-BOLD_CHARACTER_SET_CLIENT/

/*140101 SET CHARACTER SET_RESULTS-BOLD CHARACTER SET RESULTS */;

/*140101 SET COLLATION CONNECTION BOLD_COLLATION_CONNECTION */;

/*140111 SET SQL_NOTES-BOLD_SQL_NOTES */;

Dump completed on 2025-04-01 9:01:50

Activate Windows

Go to Settings to activate Windows.
MySQL dump 10.13 Distrib 8.0.32, for Win64 (x86_64)

Host: localhost Database: bdviagem

Server version 8.0.32

/*140101 SET @OLD_CHARACTER_SET_CLIENT-@@CHARACTER_SET_CLIENT

/*140101 SET @OLD_CHARACTER_SET_RESULTS-@@CHARACTER_SET_RESULTS*/;

/*140101 SET GOLD COLLATION_CONNECTION @@COLLATION CONNECTION */;

/*150503 SET NAMES utf8 */;

/*140103 SET @OLD_TIME_ZONE=@@TINE_ZONE */;

/*140103 SET TIME ZONE=+00:00 */;

/*140014 SET @OLD_UNIQUE_CHECKS-@@UNIQUE CHECKS, UNIQUE_CHECKS=0"/;

/*140014 SET @OLD_FOREIGN_KEY_CHECKS-@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0*/;

/*140101 SET @OLD_SQL_NODE=@@SQL_NODE, SQL_MODE="NO_AUTO_VALUE_ON_ZERO* */; /*140111 SET @OLD_SQL_NOTES @@SQL_NOTES, SQL NOTES=0 */;

Table structure for table pais"

DROP TABLE IF EXISTS "pais";

/*140101 SET @saved_cs_client = @@character_set_client */;

/*150503 SET character_set_client = utf8mb4*/;

CREATE TABLE `pais (

"idpais" int unsigned NOT NULL AUTO INCREMENT,

nome varchar(45) NOT NULL,

PRIMARY KEY (`idpais")

) ENGINE=InnoDB AUTO INCREMENT 3 DEFAULT CHARSET=utf8mb3;

/*140101 SET character_set_client @saved_cs_client */;

Dumping data for table 'pais

LOCK TABLES "pais WRITE;

/*140000 ALTER TABLE "pais DISABLE KEYS */;

INSERT INTO `pais VALUES (1, 'Brasil'), (2, 'EUA");

/*140000 ALTER TABLE "pais" ENABLE KEYS */;

UNLOCK TABLES;

/*140103 SET TIME ZONE @OLD_TIME ZONE*/;

Activate Windows

Go to Settings to activate Windows

ENG

PTB2
